kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-deltaker-bff
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-deltaker-bff.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 45
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-deltaker-flate
        - application: veilarbpersonflate
          namespace: poao
    outbound:
      rules:
        - application: amt-arrangor
        - application: amt-person-service
        - application: amt-deltaker
        - application: poao-tilgang
          namespace: poao
  env:
    - name: AMT_ARRANGOR_SCOPE
      value: api://dev-gcp.amt.amt-arrangor/.default
    - name: AMT_ARRANGOR_URL
      value: http://amt-arrangor
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: AMT_PERSONSERVICE_SCOPE
      value: api://dev-gcp.amt.amt-person-service/.default
    - name: AMT_PERSONSERVICE_URL
      value: http://amt-person-service
    - name: AMT_DELTAKER_SCOPE
      value: api://dev-gcp.amt.amt-deltaker/.default
    - name: AMT_DELTAKER_URL
      value: http://amt-deltaker

  gcp:
    sqlInstances:
      - name: amt-deltaker-bff
        collation: nb_NO.UTF8
        type: POSTGRES_14
        databases:
          - name: amt-deltaker-bff
            envVarPrefix: DB
