kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-deltaker-bff
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-deltaker-bff.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true

  gcp:
    sqlInstances:
      - name: amt-deltaker-bff
        collation: nb_NO.UTF8
        type: POSTGRES_14
        databases:
          - name: amt-deltaker-bff
            envVarPrefix: DB
